name: debug machine
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config-base64: ${{ secrets.CONFIG }}
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
